In [1]:
import numpy as np

# numpy contains multidimensional data structures

## ARRAY

In [4]:
# difference between list and array

list1 = [10,20,30]        # lists are heterogenours (elements can be different)
arr1 = np.array(list1)    # array is homogenours(all elements same type)

print(list1)
arr1

[10, 20, 30]


array([10, 20, 30])

## ARANGE()

In [9]:
# arange() returns evenly spaced values within a given interval
arr2 = np.arange(10,20,2)
arr2

array([10, 12, 14, 16, 18])

In [18]:
# LISTS
list2 = [40,50,60]
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

## 2 DIMENSIONAL ARRAY

In [19]:
# 2DIMENSIONAL ARRAY
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
# 2DIMENSIONAL SHAPE
arr3.shape

# (2,3) 2DIMENSIONAL ARRAY
# 2 - number of lists in first instance
# 3 - inner elements second instance

(2, 3)

## 3 DIMENSIONAL ARRAY

In [26]:
# 3DIMENSIONAL ARRAY
arr3dim = np.array ([[[1,2,3],[3,4,5]],[[5,6,7], [7,8,9]]])
arr3dim


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [27]:
# 3DIMENSIONAL SHAPE
arr3dim.shape

# (2,2,3)
# 2 elements (2 lists)
# 2 lists within lists
# 3 elements within a list

(2, 2, 3)

In [30]:
# 3DIMENSIONAL SHAPE
arr3dim = np.array ([[[1,2,3],[5,6,7],[7,8,9]]])
arr3dim
print(arr3dim.shape)

(1, 3, 3)


## ARITHMETIC OPERATIONS

In [31]:
arr3dim * 2

array([[[ 2,  4,  6],
        [10, 12, 14],
        [14, 16, 18]]])

In [36]:
arr1

array([10, 20, 30])

In [39]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [40]:
arr1 * arr3


array([[ 100,  400,  900],
       [ 400, 1000, 1800]])

In [46]:
# ACCESS INDEX 1
arr3[0]     # access first item
arr3[0][1]  # access first item within second item


np.int64(20)